const ACTIONS = {
  CALCULATE_GWA : 'CALCULATE_GWA',
  ADD_SUBJECT : 'ADD_SUBJECT',
  DELETE_SUBJECT : 'DELETE_SUBJECT',
  CHANGE_INPUTFIELD: 'CHANGE_INPUTFIELD',
  CALCULATE_SUBJGRADES: 'CALCULATE_SUBJGRADES'
}

export default ACTIONS;